subdir-ccflags-y += -Werror -Wno-error=date-time -Wno-date-time

ccflags-y += -I$(srctree)/drivers/media/platform/tegra
ccflags-y += -I$(srctree)/drivers/video/tegra/camera

obj-$(CONFIG_VIDEO_IMX185) += imx185.o
obj-$(CONFIG_VIDEO_IMX185) += imx185_v1.o
obj-$(CONFIG_VIDEO_IMX477) += imx477.o
obj-$(CONFIG_VIDEO_IMX219) += imx219.o
obj-$(CONFIG_VIDEO_IMX268) += imx268.o
obj-$(CONFIG_VIDEO_IMX274) += imx274.o
obj-$(CONFIG_VIDEO_IMX318) += imx318.o
obj-$(CONFIG_VIDEO_LC898212) += lc898212.o
obj-$(CONFIG_VIDEO_OV5693) += ov5693.o

obj-$(CONFIG_VIDEO_OV9281) += ov9281.o
obj-$(CONFIG_VIDEO_OV9281) += imx183.o
obj-$(CONFIG_VIDEO_OV9281) += imx226.o
obj-$(CONFIG_VIDEO_OV9281) += imx250.o
obj-$(CONFIG_VIDEO_OV9281) += imx252.o
obj-$(CONFIG_VIDEO_OV9281) += imx273.o
obj-$(CONFIG_VIDEO_OV9281) += imx290.o
obj-$(CONFIG_VIDEO_OV9281) += imx296.o
obj-$(CONFIG_VIDEO_OV9281) += imx296_vgl.o
obj-$(CONFIG_VIDEO_OV9281) += imx327c.o
obj-$(CONFIG_VIDEO_OV9281) += imx392.o
obj-$(CONFIG_VIDEO_OV9281) += imx412.o
obj-$(CONFIG_VIDEO_OV9281) += imx415.o

obj-$(CONFIG_VIDEO_OV10823) += ov10823.o
obj-$(CONFIG_VIDEO_OV23850) += ov23850.o
obj-$(CONFIG_I2C_IOEXPANDER_PCA9570) += pca9570.o
obj-$(CONFIG_VIDEO_TC358840) += tc358840.o
obj-$(CONFIG_VIDEO_LT6911UXC) +=lt6911uxc.o
obj-$(CONFIG_I2C_IOEXPANDER_SER_MAX9295) += max9295.o
obj-$(CONFIG_I2C_IOEXPANDER_DESER_MAX9296) += max9296.o
obj-$(CONFIG_VIDEO_IMX390) += imx390.o
