@startuml
!theme plain
clock "External trigger" as TRIG  with period 1250 pulse 250
clock "Exposure"         as EXP   with period 1250 pulse 750
clock "Flash output"     as FLASH with period 1250 pulse 500 offset 750

@0
@2250

@enduml