@startuml
!theme plain
binary "External trigger"         as TRIG
binary  "Exposure (1: external)"  as EXT
binary "Exposure (2: pulsewidth)" as PULS
clock  "Exposure (8: overlap)"    as OVL  with period 1000 pulse 990

@TRIG
0 is high
250 is low
1000 is high
1500 is low
2000 is high
2250 is low

@EXT
0 is high
750 is low
1000 is high
1750 is low
2000 is high
2750 is low
EXT@750 <-> @1000 : Tmin

@PULS
0 is high
250 is low
1000 is high
1500 is low
2000 is high
2250 is low

@enduml